### ISSUE TITLE
One click Blast Furnace

### ISSUE THREAD

**Issue by Pvrps** [Magnusrn/Plugins#12]
Hey! Would you be willing to add an enhancement to one click blast furnace plugin so that it will only equip the ice gloves once the XP drop happens? That way you can just spam click without worry that the ice gloves will be equipped before the XP drop, resulting in lost XP.

If you don't have time to implement this, let me know and I'd be glad to look into it and open a pull request.

**Comment by Magnusrn** [comment]
I think you might be running a different method, should never require specific timing or miss xp drops(other than for 1 bar).

There's a video in my disc with example 
https://discord.gg/UnqwvPzS
https://cdn.discordapp.com/attachments/942952848696705034/953154640466280468/Untitled.mp4

**Comment by Magnusrn** [comment]
https://cdn.discordapp.com/attachments/942952848696705034/953154640466280468/Untitled.mp4

**Comment by Pvrps** [comment]
Ah yes, you're right. I wasn't pre-loading the dispenser before turning on the plugin.

I will close this issue. Thanks!
