### ISSUE TITLE
Cox Raid Scouter - Scout for larger sized raids

### ISSUE THREAD

**Issue by datashe12** [Magnusrn/Plugins#2]
Hello,
Currently any layouts with 6 or more rooms are abandoned with the debug message "Raid is incorrect size",

Could a way to scout for raids larger than 5 rooms be added? I understand this isn't especially useful, but I would make use of it if it was a feature

**Comment by Magnusrn** [comment]
This would be nice to have but It'd require a decent rewrite, was much easier to just hardcode for 3c2p so not something I'll have time to add I'm afraid. Anytime I need a large raid I just manual scout or ask someone in wdr scout trading to do it for me

**Comment by datashe12** [comment]
Ah ok, definitely not useful enough for a lot of effort 😄 
Thanks for the reply
