### ISSUE TITLE
Blastfurnace, won't unload bars and take out ores (GOLD)

### ISSUE THREAD

**Issue by Ahlander93** [Magnusrn/Plugins#5]
Hello, it won't unload gold bars from the furnace and will not withdraw gold ores from bank. I did all you wrote, I put 27 gold ores in hopper, i have bank fillers. What am I doing wrong or is it the script?? :)

**Comment by Magnusrn** [comment]
Pretty sure it's working fine, I'll upload a video to my disc shortly as a lot of people have had issues with set-up, lots to consider.

In your case you might not be in the main bank tab, or might not have 1 dose and 4 dose staminas?

**Comment by Magnusrn** [comment]
https://user-images.githubusercontent.com/50274421/158309693-bbcb22e0-5487-41c3-b4c2-4829683284f7.mp4

Hopefully this will explain

**Comment by Ahlander93** [comment]
Perfect, thank you :)
