### ISSUE TITLE
Mory Bloods Issue

### ISSUE THREAD

**Issue by jdaws62** [Magnusrn/Plugins#7]
Hey mate, 
While on the path from POH to Blood altar using the shitty agility shortcut, the long room Region id 14233 (darkish area before blood altar) you will currently tele to house if you red click while running between the start and the end tunnel. At first i thought it was a problem with the run energy but believe its possibly just triggering the begin sequence again as all the parameters are being met. Could you possibly look into this and null this area? Cheers

**Comment by Magnusrn** [comment]
Yeah I kinda forgot about this tbh, I'll try do this within the next few days, I just mismapped a bit of the tunnels

**Comment by Magnusrn** [comment]
Solved
